AWSTemplateFormatVersion: 2010-09-09
Description: IAM - Policy for AWS Training

Resources:
  TestPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: testPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeRegions
            Resource: "*"

  # TestPolicy:
  #   Type: AWS::IAM::ManagedPolicy
  #   Properties:
  #     ManagedPolicyName: testPolicy
  #     PolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Action:
  #             - ec2:DescribeRegions
  #             - ec2:DescribeVpcs
  #           Resource: "*"